name: Node.js Package

on:
  release:
    types: [ created ]
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2

      - name: Authenticate with GitHub Packages
        run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" > ~/.npmrc

      - run: bun install
      - run: bun run build

      - name: Publish to GitHub Packages
        run: bun publish
        env:
          NPM_CONFIG_TOKEN: ${{ secrets.GITHUB_TOKEN }}
